alias mvnw='./mvnw'
alias gradlew='./gradlew'
alias rr='ranger-cd'
alias ssh='backpack'
alias shrug="printf '¯\_(ツ)_/¯' | pbcopy"
alias sdiff='sdiff --diff-program=colordiff -w $(($(tput cols) - 10))'
alias shreload='source $HOME/.zshrc'
alias omzreload='source $ZSH/custom/**.zsh' 
alias grep='ggrep'
alias dps='docker ps | less'
alias toz='cd $ZSH/custom'
alias cat='gcat'
alias cut='gcut'
alias grep='ggrep'
alias sed='gsed'
alias lzd='lazydocker'
