alias mvnw='./mvnw'
alias gradlew='./gradlew'
alias rr='ranger-cd'
alias sdiff='sdiff --diff-program=colordiff -w $(($(tput cols) - 10))'
alias shreload='source $HOME/.zshrc'
alias dps='docker ps | less'
alias toz='cd $ZSH/custom'
